### PR TITLE
feat: Detach pin on double click

### PR DESCRIPTION
**Pull request by rzaaeeff**
When you click on a pin, all connections of it will be deleted.

Note: I've also moved your code to new function called "deleteConnections(arr)" to avoid duplicate code. Because, I needed to use same code.

### CODE REVIEW

**Comment by adilek** [comment]
Hi,
Thanks for the code. It looks good to me. However I did some code for selection and deletion of connections. Additionally selection and deletion of components are on my local computer. I have to review and push it into master repo. Could you rebase your patch after my updates this Friday (or Saturday)?

**Comment by rzaaeeff** [comment]
Hi @adilek,

It's okay for me. Just notify me whenever you push new changes.

**Comment by adilek** [comment]
Hi @rzaaeeff,
I just uploaded all my local commits. Please rebase your commits.

Regarding fixing typos please send the pull request separately. And I will merge it.

Regarding double click for disconnecting the line is little unclear from UX point-of-view. Let's discuss it in detail.

**Comment by rzaaeeff** [comment]
Hello @adilek,
You can attach two components by consecutively clicking on their pins. But how do you detach them? I think user should be able to delete Connection Line without deleting component itself, and I thought double click would be good way to go. 

Explanation: "User double clicks on a pin to delete all lines connected to this particular pin.

What do you think?

**Comment by adilek** [comment]
Could you show similar experience examples from other software?

In my patch you can delete connection line by selecting line.

**Pull request closed without merging**
